#166240949 The user is able to login into his/her account on Author's Haven
andela/tesla-ah-frontend pull request #13
Opened 2019-08-07 15:32 UTC by Diama1

### What does this PR do?
- Create a user interface which helps users to login
### Description of a task to be completed
- Creating a UI for users to Login
- Make a Login remote request to the server

2019-08-13 07:15 UTC, EmyRukundo approved these changes

2019-08-13 17:58 UTC, deschantkn approved these changes

2019-08-13 17:58 UTC, deschantkn commented on @
> +ft(login):The user is able to login into his/her account
Hello @Diama1 I am just curious about the role this file is playing here.

2019-08-13 17:58 UTC, deschantkn commented on __tests__/components/login.test.js
> +    it('should make a request to the server', () => {
This test doesn't appear to have an assertion, there is no `expect` statement in it. Would you kindly explain what you are testing for here?

2019-08-15 10:33 UTC, mifeille approved these changes

2019-08-15 16:52 UTC, eliemugenzi requested changes

2019-08-15 16:52 UTC, eliemugenzi commented on @
> +# Please enter the commit message for your changes. Lines starting
Good job @Diama1 , please explain to us the use of this file

2019-08-15 18:12 UTC, eliemugenzi approved these changes

2019-08-16 06:22 UTC, merged