#166240947 Implements password reset
andela/tesla-ah-frontend pull request #19
Opened 2019-08-13 09:48 UTC by mifeille

#### What does this PR do?
This PR will enable users to view and edit their profile

#### Description of Task to be completed?
- Adds reset password forms
- Adds a reset password link to the login page
- Adds redux logic
- Tests components, actions, and reducers

#### How should this be manually tested?
This PR can be tested by cloning this branch and running the development server with this command `yarn dev`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#166240947

2019-08-16 09:43 UTC, deschantkn approved these changes

2019-08-16 09:43 UTC, deschantkn commented on src/components/pages/ResetPasswordEmail.js
> +  componentDidMount() {
Hello @mifeille, would you kindly delete this unused method?

2019-08-16 13:03 UTC, eliemugenzi requested changes

2019-08-16 13:03 UTC, eliemugenzi commented on src/components/pages/ApplyPasswordForm.js
> +          <input
We have reusable TextInput components, check them out.

2019-08-16 13:03 UTC, eliemugenzi commented on src/index.js
> +import '../node_modules/bootstrap/dist/css/bootstrap.min.css';
This is no longer necessary since we have Bootstrap imported in our HTML file.

2019-08-18 08:38 UTC, eliemugenzi approved these changes
Looks Good to Approve (LGTA). Good job @mifeille.

2019-08-18 10:49 UTC, EmyRukundo approved these changes

2019-08-19 18:37 UTC, merged