#166240939 Setup Redux
andela/tesla-ah-frontend pull request #2
Opened 2019-07-29 17:45 UTC by eliemugenzi

### what does this PR do?
- Setup and a simple implementation of Redux
### Description of a task to be completed
- create a redux folder structure
- Install redux-related dependencies
- Create a redux store and reducers
- Create simple actions and action types
### How should it be manually tested?
- Install Redux Devtools chrome extension and inspect the app through it.
### Any background context you want to provide?
- Everyone has to create actions and reducers according to the feature he is working on, but the boilerplate is set up for you.
### What are the relevant pivotal tracker stories?
- [#166240939](https://www.pivotaltracker.com/story/show/166240939)
### Screenshots

![Screen Shot 2019-07-29 at 19 41 14](https://user-images.githubusercontent.com/22316636/62069817-6c37ff80-b239-11e9-836d-eaf86c73392a.png)

2019-07-30 07:36 UTC, mifeille approved these changes

2019-07-30 11:04 UTC, EmyRukundo approved these changes

2019-07-30 12:35 UTC, Diama1 approved these changes

2019-07-30 12:36 UTC, rukundoeric approved these changes

2019-07-30 17:10 UTC, deschantkn commented on package.json
> +    "redux-devtools-extension": "^2.13.8",
Is this not a dev dependency?

2019-07-31 05:21 UTC, Gidraf requested changes
Good work @eliemugenzi but I would suggest you create a folder called assets where all the images, style and fonts will be stored.
I will also suggest you create a utility folder where all project utilities like CONSTANT Strings will be stored, also create tests folder where all the test will be stored.

2019-07-31 05:58 UTC, eliemugenzi commented on package.json
> +    "redux-devtools-extension": "^2.13.8",
Nope

2019-07-31 06:25 UTC, eliemugenzi commented
> Good work @eliemugenzi but I would suggest you create a folder called assets where all the images, style and fonts will be stored.
> I will also suggest you create a utility folder where all project utilities like CONSTANT Strings will be stored, also create tests folder where all the test will be stored.
@Gidraf DONE.

2019-07-31 10:26 UTC, Gidraf approved these changes

2019-07-31 10:26 UTC, Gidraf commented
LGTM

2019-07-31 10:26 UTC, merged