Feedback implementation on login
andela/tesla-ah-frontend pull request #22
Opened 2019-08-16 09:12 UTC by Diama1

### What does this PR do?
- Implementing feedback on login.
### Description of a task to be completed
- Changing header once the user is logged in

2019-08-18 09:01 UTC, rukundoeric requested changes
![login-fb](https://user-images.githubusercontent.com/45217364/63222326-c2e48980-c1a6-11e9-9471-33aed15391ab.gif)
take a look at the screenshot above, when you refresh the page after login the header is going back to the initial-state as if the user is not logged-In, kindly solve It.

2019-08-21 10:50 UTC, deschantkn requested changes
Hello @Diama1 , the form is now centered on the page and that looks good. However the responsivity could still use some improvement. Have a look at this snapshot of the form on mobile:

<img width="756" alt="Screen Shot 2019-08-21 at 12 41 15" src="https://user-images.githubusercontent.com/50397889/63425818-b6179e00-c411-11e9-8e69-df98e866ae12.png">

You can see that the social login icons different sizes and the form elements are really short in width. I think you can improve the following points:

1. The social icons should span the full width of the form on mobile.
2. You could also decrease the margin to the left and right of the form so the elements can be larger
3. When a user clicks on the login button they should a spinner while the request is still processing, that would be better UX.

2019-08-26 10:15 UTC, deschantkn approved these changes

2019-08-26 17:34 UTC, rukundoeric approved these changes

2019-08-29 07:59 UTC, mifeille approved these changes

2019-08-29 10:35 UTC, eliemugenzi approved these changes

2019-08-29 10:35 UTC, merged