#166240967 Add search functionality to the project
andela/tesla-ah-frontend pull request #23
Opened 2019-08-19 22:53 UTC by eliemugenzi

### What does this PR do?
> Add search functionality to Authors Haven

### Description of a task to be completed?
A user will be able to search an article by:
- Its author
- Its title
- Its tags

2019-08-26 13:13 UTC, bdushimi requested changes

2019-08-26 13:13 UTC, bdushimi commented on __tests__/components/searchResults.test.js
> +  test('If an author has no articles yet!', () => {
@eliemugenzi test case description is not showing the condition under test.

2019-08-26 13:13 UTC, bdushimi commented on __tests__/components/searchResults.test.js
> +  test('Should receive new props...', () => {
@eliemugenzi this test does not have assertions!

2019-08-26 13:13 UTC, bdushimi commented on __tests__/components/signup.test.js
> +    test('It should throw errors', () => {
@eliemugenzi when would it throw the error?

2019-08-26 13:13 UTC, bdushimi commented on __tests__/components/signup.test.js
> +    });
@eliemugenzi  add an assertion to this test.

2019-08-26 13:13 UTC, bdushimi commented on __tests__/forms/search.test.js
> +    };
@eliemugenzi add an assertion to this test.

2019-08-26 13:13 UTC, bdushimi commented on __tests__/forms/search.test.js
> +  });
@eliemugenzi add an assertion to this test.

2019-08-26 13:13 UTC, bdushimi commented on __tests__/forms/search.test.js
> +  });
@eliemugenzi add an assertion to this test

2019-08-26 15:35 UTC, eliemugenzi commented on __tests__/components/searchResults.test.js
> +  test('If an author has no articles yet!', () => {
The condition is based on the props defined...

2019-08-26 19:01 UTC, EmyRukundo approved these changes

2019-08-26 19:26 UTC, deschantkn commented
Hello @eliemugenzi great work implementing the search without having to hit enter to submit. But I'm wondering why there is a 3 character minimum limit to search for a key word, also sometimes there is a message which says `you have made a bad request`, how is it different from the one that says `You should have provided at least 3 characters long for keywords`.

2019-08-26 22:55 UTC, eliemugenzi commented on __tests__/redux/actions/article/searchAction.test.js
> +import {
> Hello @eliemugenzi great work implementing the search without having to hit enter to submit. But I'm wondering why there is a 3 character minimum limit to search for a key word, also sometimes there is a message which says `you have made a bad request`, how is it different from the one that says `You should have provided at least 3 characters long for keywords`.

@deschantkn , when is the `You have made a bad request`  being thrown? It should happen if the user makes a remote request with a wrong query parameter. And I think the request I made in my action is valid. Kindly come and show me that case. Thanks for the feedback.

2019-08-27 07:08 UTC, eliemugenzi commented
> Hello @eliemugenzi great work implementing the search without having to hit enter to submit. But I'm wondering why there is a 3 character minimum limit to search for a key word, also sometimes there is a message which says `you have made a bad request`, it seems to be random. How is it different from the one that says `You should have provided at least 3 characters long for keywords`?.

2019-08-27 07:10 UTC, eliemugenzi commented
@deschantkn , when is the `You have made a bad request`  being thrown? It should happen if the user makes a remote request with a wrong query parameter. And I think the request I made in my action is valid. Kindly come and show me that case. Thanks for the feedback. The minimum of 3 characters is the backend validation.

2019-08-27 07:59 UTC, Diama1 approved these changes

2019-08-27 09:21 UTC, UhiriweAudace commented
Kindly @eliemugenzi  resolve those Hound CI issues. Thanks!

2019-08-27 11:54 UTC, rukundoeric approved these changes

2019-08-27 11:57 UTC, merged