#166240955 Rating Article Functionality Added
andela/tesla-ah-frontend pull request #29
Opened 2019-08-29 07:27 UTC by UhiriweAudace

#### What does this PR do?
- In this PR, I implemented the rating article functionality
#### Description of Task to be completed?
- The logged-in users will be able to submit their ratings on a specific article
- The logged-in users will be able to view the ratings of a specific article
- The user will be able to update their ratings on a specif article
#### How should this be manually tested?
- Clone the repository, then switch to this branch `ft-rating-article-166240955`
- Install all dependencies by writing the following command: 
       - `yarn install`
- Then run the application with the following command:
       - `yarn dev`
- To run the test, simply run this command: `yarn test`
#### Any background context you want to provide?
- **N/A**
#### What are the relevant pivotal tracker stories?
- [#166240955](https://www.pivotaltracker.com/n/projects/2350798/stories/166240955)
#### Screenshots (if appropriate)

#### Questions:

2019-09-02 07:54 UTC, EmyRukundo reviewed
@UhiriweAudace 
   I think you should remove these comments.

2019-09-02 07:55 UTC, EmyRukundo commented on src/redux/actions/users/login.actions.js
> +    // const previousLink = sessionStorage.getItem('previousLink');
these comments

2019-09-02 07:56 UTC, EmyRukundo approved these changes

2019-09-02 12:30 UTC, deschantkn commented
Test comment

2019-09-04 07:12 UTC, UhiriweAudace commented on src/redux/actions/users/login.actions.js
> +    // const previousLink = sessionStorage.getItem('previousLink');
resolved

2019-09-10 10:48 UTC, eliemugenzi requested changes

2019-09-10 10:48 UTC, eliemugenzi commented on __tests__/redux/actions/getArticles.test.js
> +    //     status: 200,
Please delete these commented lines

2019-09-10 10:48 UTC, eliemugenzi commented on src/assets/scss/base/_common.scss
>  // .likeButton p{
Please delete these commented code

2019-09-10 11:08 UTC, eliemugenzi approved these changes

2019-09-10 15:02 UTC, rukundoeric approved these changes

2019-09-12 10:33 UTC, merged