#166240959 Users should be able to like and or dislike articles
andela/tesla-ah-frontend pull request #34
Opened 2019-09-02 07:47 UTC by EmyRukundo

**What does this PR do?**

Users should be able to like and or dislike articles

**Description of task to be completed?**

Users should be able to like and or dislike articles when he or she are logged in

**How should this be manually tested?**

Cloning into this branch and trying to like and dislike an article

**What are the relevant pivotal tracker stories?**

#166240959

Screenshots

2019-09-03 19:18 UTC, rukundoeric approved these changes

2019-09-03 21:19 UTC, UhiriweAudace commented
Kindly, @EmyRukundo  fix those Hound CI issues

2019-09-04 06:31 UTC, eliemugenzi requested changes

2019-09-04 06:31 UTC, eliemugenzi commented on src/redux/reducers/likeAndDislike.reducer.js
> +//   console.log('----', payload);
Remove this comment

2019-09-04 06:31 UTC, eliemugenzi commented on src/components/common/LikeAndDislike.js
> +          onClick={() => this.handleLikeArticle(this.props.slug)}
Remove these comments

2019-09-04 06:45 UTC, EmyRukundo commented on src/redux/reducers/likeAndDislike.reducer.js
> +//   console.log('----', payload);
@eliemugenzi , Done it, thanks

2019-09-04 06:45 UTC, EmyRukundo commented on src/components/common/LikeAndDislike.js
> +          onClick={() => this.handleLikeArticle(this.props.slug)}
corrected it

2019-09-04 07:11 UTC, UhiriweAudace approved these changes

2019-09-04 07:23 UTC, eliemugenzi approved these changes

2019-09-04 09:28 UTC, deschantkn approved these changes

2019-09-04 11:40 UTC, merged