chore(setup-hound): Enable hound to some error
andela/tesla-ah-frontend pull request #9
Opened 2019-08-05 08:19 UTC by rukundoeric

#### What does this PR do?
- I configured the houndci to automate code review on any pull request
#### Description of Task to be completed?
-  setup hound
#### How should this be manually tested?
- Simply create a pull request with some error
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
[#167565116](https://www.pivotaltracker.com/story/show/167565116)
#### Screenshots (if appropriate)
#### Questions:

2019-08-05 08:23 UTC, eliemugenzi requested changes

2019-08-05 08:23 UTC, eliemugenzi commented on .hound.yml
> +  config_file: .eslintrc.json
ESLint config file is called `.eslintrc` not `.eslintrc.json`

2019-08-05 16:09 UTC, deschantkn approved these changes

2019-08-06 09:44 UTC, EmyRukundo approved these changes

2019-08-07 14:39 UTC, eliemugenzi approved these changes

2019-08-07 15:33 UTC, merged